services:
  web:
    build:
      context: .
      dockerfile: 'Dockerfile'
    
    command: sh -c 'python manage.py makemigrations && python manage.py migrate && python manage.py loaddata */fixtures/*.json && python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/code/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: postgres:13.0-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

