# Generated by Django 4.2.2 on 2023-06-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coffee_machine", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coffee",
            name="ingredient",
        ),
        migrations.AddField(
            model_name="coffee",
            name="ingredient_mix",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
