# Generated by Django 4.2.2 on 2023-06-23 16:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coffee_machine", "0003_alter_coffee_strength_alter_ingredient_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="is_removed",
        ),
    ]
