# Generated by Django 4.2.2 on 2023-06-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coffee_machine", "0006_alter_coffee_strength"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coffee",
            name="strength",
            field=models.CharField(
                blank=True, choices=[(1, 1), (2, 2), (3, 3)], max_length=20, null=True
            ),
        ),
    ]
