# Generated by Django 4.2.2 on 2023-06-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coffee_machine", "0007_alter_coffee_strength"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coffee",
            name="strength",
            field=models.CharField(
                blank=True,
                choices=[("NORMAL", 1), ("STRONG", 2), ("EXTRA_STRONG", 3)],
                max_length=20,
                null=True,
            ),
        ),
    ]
