# Generated by Django 4.2.2 on 2023-06-23 18:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coffee_machine", "0010_alter_ingredient_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Coffee",
            new_name="Order",
        ),
    ]
