# Generated by Django 4.2.2 on 2023-06-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coffee_machine", "0011_rename_coffee_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="strength",
            field=models.CharField(
                choices=[("NORMAL", 1), ("STRONG", 2), ("EXTRA_STRONG", 3)],
                default="Coffee",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
